ask/ask_krutyakov/urls.py
from django.conf.urls import patterns, include, url
from say import views, view

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ask_krutyakov.views.home', name='home'),
    # url(r'^blog/', 'blog.urls'),
    url(r'^$', views.index),
    url(r'^search', views.search),
    url(r'^question/*$', views.question),
    url(r'^login/{0,1}$', views.login),
    url(r'^logout', views.logout_view),
    url(r'^settings/{0,1}$', views.signup),
    url(r'^sayhello/', view.hello),
    url(r'^register', views.register),
    url(r'^ask', views.ask),
    url(r'^delete_question', views.delete_question),
    url(r'^delete_answer', views.delete_answer),
    url(r'^admin/', admin.site.urls),
    url(r'^like', views.like),
    url(r'^set_correct', views.set_correct),
    url(r'^answer', views.answer),
    url(r'^tag/(?P<tagname>.*)', views.tag_list),
)

ask/say/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User
from django import forms
from djangosphinx.models import SphinxSearch

class MyUser(AbstractUser):
  avatar = models.ImageField(upload_to='/avatar')
  rating = models.IntegerField()
  class Meta:
    db_table = 'user'

class UserForm(forms.ModelForm):
  class Meta:
    model = MyUser
    fields = ['username', 'email', 'avatar']

class RegisterForm(forms.ModelForm):
  password = forms.CharField(widget=forms.PasswordInput())
  class Meta:
    model = MyUser
    fields = ['username', 'email']

class Tag(models.Model):
  word = models.CharField(max_length = 30)

class Question(models.Model):
  title = models.CharField(max_length = 100)
  content = models.TextField()
  author = models.ForeignKey('MyUser')
  date = models.DateTimeField(auto_now_add = True)
  tags = models.ManyToManyField('Tag')
  rating = models.IntegerField(null=False, default=0)
  search = SphinxSearch(weights={'title':100, 'content': 50})

class Like(models.Model):
  user = models.ForeignKey('MyUser')
  question = models.ForeignKey('Question')

class Answer(models.Model):
  question = models.ForeignKey('Question')
  content = models.TextField()
  author = models.ForeignKey('MyUser')
  date = models.DateTimeField(auto_now_add = True)
  is_true = models.BooleanField()
  search = SphinxSearch(weights={'content':50})

class AnswerForm(forms.ModelForm):
  def __init__(self, *args, **kwargs):
    self.author = kwargs.pop('user', None)
    self.question = kwargs.pop('question', None)
    super(AnswerForm, self).__init__(*args, **kwargs)
    
  def save(self, commit=True):
    obj = super(AnswerForm, self).save(commit=False)
    obj.author = self.author
    obj.question = self.question
    if commit:
      obj.save()
    return obj
  
  class Meta:
    model = Answer
    exclude = ['author','date','is_true','question']

class AskForm(forms.ModelForm):
  tags = forms.CharField(max_length = 100, required = False)
  def __init__(self, *args, **kwargs):
    self.author = kwargs.pop('user', None)
    super(AskForm, self).__init__(*args, **kwargs)
    
  def save(self, commit=True):
    obj = super(AskForm, self).save(commit=False)
    obj.author = self.author
    if commit:
      obj.save()
    return obj
  
  class Meta:
    model = Question
    exclude = ['author','date','rating','tags']

ask/templates/ask.html
{% extends "base.html" %}
{% block title %}Ask{% endblock %}
{% block main %}
  <div class="col-md-8">
  <h1>New Question</h1>
  
  <div class="alert alert-danger" id="alert" style="display:none;">
    <a class="close">&times;</a>
    <div class="alert_message"></div>
  </div>
  
  <form action="" method="POST" id="ask_form" style="width:200px; margin:20px 0;">
    {% csrf_token %}
    <div class="form-group">
      {{ form }}
    </div>
    <div class="form-group">
      <input type="submit" value="ASK!" class="btn btn-primary">
    </div>
  </form>
{% endblock %}

{% block scripts %}
  <script type="text/javascript" src="/cookie/jquery.cookie.js"></script>
  <script type="text/javascript">
    $('#ask_form').submit(function() {
      $.ajaxSetup({
        beforeSend: function(xhr, settings) {
          xhr.setRequestHeader("X-CSRFToken", $.cookie('csrftoken'))
        }
      })
      var _title = $('#ask_form #id_title').val()
      var _text = $('#ask_form #id_content').val()
      var _tags = $('#ask_form #id_tags').val()
      $.post(window.location.href, {title: _title, content: _text, tags: _tags})
      .done(function(data) {
        if (data.status == 'OK') {
          window.location.href = location.protocol + '//'+location.host+data.redirect;
        } else {
          al = $('#alert')
          al.show()
          al.children(".alert_message").text(data.message)
        }
      })
      return false;
    })
    
    $('.close').click(function() {
      $('.alert').hide();
    })
  </script>
{% endblock %}

ask/templates/base.html
{% load best_users %}
{% load best_tags %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link href="/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="/main.css" rel="stylesheet">
    <title>{% block title %}Basic page{% endblock %}</title>
  </head>
  <body>
      <header class="container">
        <nav class="navbar navbar-default" role="navigation">
          <div class="navbar-inner">
            <div class="container-fluid">
              <div class="navbar-header">
                <a href="/" class="navbar-brand">AskPupkin</a>
              </div>
              <ul class="nav navbar-nav">
                <li>
                  <form class="navbar-form" role="search" action="/search">
                    <div class="input-group">
                      <input type="text" name="q" class="form-control" autocomplete="off" placeholder="Search"/>
                      <div class="input-group-btn">
                        <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
                      </div>
                    </div>
                  </form>
                </li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                  <form class="navbar-form">
                  <a class="btn btn-success btn-sm" href="/ask">ASK!</a>
                  </form>
                </li>
                <li>
                  <img src="{{user.avatar.url}}" width="45" height="45" class="nav-img img-thumbnail" id="#user_avatar" alt="Avatar">
                </li>
                <li class="nav-user">
                  <span class="user_name">{{user.name|escape}}</span>
                  <div class="navbar-inner">
                    <a href="/settings" style="margin-right:10px;">settings</a><br/>
                    <a href="/logout">log out</a>
                  </div>
                </li>
                  {% else %}
                <li class="active">
                  <a href="/login">log in</a>
                </li>
                <li>
                  <a href="/register">register</a>
                </li>
                  {% endif %}
              </ul>
            </div>
          </div>
        </nav>
      </header>
      
  <div class="wrapper container">
      <div class="row">
        <main class="col-md-8">
          {% block main %}{% endblock %}
        </main>
        <footer class="col-md-4">
          {% best_tags  %}
          {% best_users %}
        </footer>
      </div>
    </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="/bootstrap/js/bootstrap.min.js"></script>
  {% block scripts %}{% endblock %}
  </body>
</html>

ask/templates/best_tags.html
<h2>Popular Tags</h2>
<ul class="tag-cloud tag-list" style="padding-left:0px;">
{% for tag in best_tags %}
  <li class="tag"><a class="tag-size-{{tag.count}}" href="/tag/{{tag.word|escape}}">{{ tag.word|escape }}</a>,</li> 
{% endfor %}
</ul>

ask/templates/best_users.html
<h2>Best Members</h2>
<ul class="best_members_list">
{% for member in best_users %}
  <li class="user_name"><a href="/user?id={{member.id}}">{{ member.username|escape }}</a></li>
{% endfor %}
</ul>

ask/templates/index.html
{% extends "base.html" %}
{% block title %}Main page{% endblock %}

{% load question_info %}
{% block main %}
  <div class="row">
    <h1 class="col-md-8">Questions</h1>
  </div>
  Order by: <a href="/?order=date">date</a> <a href="/?order=rating">rating</a>
  {% for question in question_list %}
    {% question_info question %}
  {% endfor %}
  <div class="row">
    <div class="col-md-12">
      <ul class="pagination">
        {% if question_list.number > 2 %}
          <li><a href="{{url}}&page=1">1</a></li>
        {% endif %}
        {% if question_list.has_previous %}
          <li><a href="{{url}}&page={{ question_list.previous_page_number }}">{{ question_list.previous_page_number }}</a></li>
        {% endif %}
          <li><a href="{{url}}&page={{ question_list.number }}">{{ question_list.number }}</a></li>
        {% if question_list.has_next %}
          <li><a href="{{url}}&page={{ question_list.next_page_number}} ">{{question_list.next_page_number}}</a></li>
        {% endif %}
        {% if question_list.number < pagenum_minus_one %}
          <li><a href="{{url}}&page={{ question_list.paginator.num_pages }}">{{ question_list.paginator.num_pages }}</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
{% endblock %}

{% block scripts %}
  <script type="text/javascript" src="/cookie/jquery.cookie.js"></script>
  <script type="text/javascript">
  var csrftoken = $.cookie('csrftoken')
  $.ajaxSetup({
    beforeSend: function(xhr, settings) {
      xhr.setRequestHeader("X-CSRFToken", csrftoken)
    }
  });
        
  $('.js_like').on('click', function() {
    var like = $(this)
    $.post("/like", {type: like.data('type'), id: like.data('id')})
      .done(function(response) {
          like.parent().children('.js_like_count').text(response.rating)
          like.removeClass('like_'+$('.js_like').data('type')).addClass('like_'+response.status).data('type', response.status)
        })
  });
  </script>
{% endblock %}

ask/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block main %}
  <div class="row">
    <div class="col-md-8">
      <h1>Log In</h1>
    </div>
  </div>
  <div class="alert alert-danger" id="alert" style="display:none;">
    <a class="close" data-dismiss="alert">&times;</a>
    <div class="alert_message"></div>
  </div>
  <div style="width:200px">
    <form action="" id="login_form" method="POST" remote="true">{% csrf_token %}
      <div class="form-group">
        <label for="username">Login</label>
        <input class="form-control" type="text" id="username" name="username" placeholder="Input your login here" autocomplete="off">
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input class="form-control" id="login_form_password" type="password" name="password" value="" autocomplete="off">
      </div>
      <div class="form-group">
        <input type="submit" value="Log in!" class="btn btn-primary"></br>
        <a href="/login/new">create new account</a>
      </div>
    </form>
  </div>
{% endblock %}

{% block scripts %}
  <script type="text/javascript" src="/cookie/jquery.cookie.js"></script>
  <script type="text/javascript">
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
          xhr.setRequestHeader("X-CSRFToken", $.cookie('csrftoken'))
        }
      })
    $('#login_form').submit(function() {
      var un = $('#login_form #username').val()
      var pw = $('#login_form #login_form_password').val()
      $.post(window.location.href, {username: un, password: pw})
      .done(function(data) {
        if (data.status == 'OK') {
          window.location.href = location.protocol + '//'+location.host+data.redirect;
        } else {
          al = $('#alert')
          al.show()
          al.children(".alert_message").text(data.err_message)
        }
      })
      return false;
    })
  </script>
{% endblock %}

ask/templates/question.html
{% extends "base.html" %}
{% block title %}{{ question.title | escape }}{% endblock %}
{% block main %}
  <h1>{{ question.title | escape }}</h1>
  {% if user == question.author %}
  <div>
    <form action="/delete_question" method="POST" name="del">
      {% csrf_token %}
      <input type="hidden" name="id" value="{{ question.id }}"/>
      <a href="#" onclick="document.del.submit()">
      <span class="glyphicon glyphicon-trash"></span>
      </a>
    </form>
  </div>
  {% endif %}
  {% for line in content %}
    <p>{{line}}</p>
  {% endfor %}
  
  <span class="glyphicon glyphicon-tags" aria-hidden="true"></span>
  <ul class="tags">
    {% for tag in question.tags.all %}
      <li>
        <a href="/tag/{{tag.word|escape}}">
          {{tag.word | escape}}
        </a>
      </li>
    {% endfor %}
  </ul>

  <div class="infopanel">
  <span class="author">
    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
    <a href="/user?id={{question.author.id}}">
      {{question.author.username | escape}}
    </a>
  </span>
  <span class="pubdate">
    <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
    {{question.date}}
  </span>
  <span class="rating">
    {% if not user.is_authenticated %}
    <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
    {% endif %}
    <span class="js_like_count">
      {{ question.rating }}
    </span>
    {% if user.is_authenticated %}
    {% csrf_token %}
    <span class="js_like like like_{{ liketype }}" data-id="{{ question.id }}" data-type="{{ liketype }}">
      <span class="glyphicon glyphicon-heart"></span>
    </span>
    {% endif %}
  </span>
  </div>
  
  <div id="answer_list">
  {% for answer in answers %}
    <div class="answer {% if answer.is_true %}alert-success{% endif %}" id="answer_{{answer.id}}">
      <div class="info">
        <img src="{{answer.author.avatar.url}}" width="50" height="50" class="img-thumbnail" alt="Avatar">
        <span class="answ_author">
          {{ answer.author.username | escape }}
        </span>
        <span class="answ_date">
          {{ answer.date }}
        </span>
        {% if user == answer.author %}
        <span class="js_answer_delete" data-id="{{ answer.id }}">
          <span class="glyphicon glyphicon-trash" ></span>
        </span>
        {% endif %}
      </div>
      {{answer.content | escape}}
      
      {% if user == question.author %}
      <form class="js_correct">
        {% csrf_token %}
        <input type="hidden" class="js_correct_id" name="id" value="{{ answer.id }}" />
        <input type="checkbox" {% if answer.is_true %}checked="checked"{% endif %} class="js_correct_input" name="checker" value="set" autocomplete="off"/> Correct
      </form>
      {% endif %}
    </div>
  {% endfor %}
  </div>
  
  {% if user.is_authenticated %}
  <form class="answer_form">
  {% csrf_token %}
    <div  class="form-group">
    <input type="hidden" value="{{ question.id }}" name="q_id" class="q_id"/>
    {{ answer_form }}
    </div>
    <input type="submit" value="Submit your answer" class="answer_form_submit btn btn-primary">
  </form>
  {% endif %}
  
  {% if answers.paginator.num_pages > 1 %}
  <div class="row">
    <div class="col-md-12">
      <ul class="pagination">
        {% if answers.number > 2 %}
          <li><a href="{{url}}&answer_id=1">1</a></li>
        {% endif %}
        {% if answers.has_previous %}
          <li><a href="{{url}}&answer_id={{ answers.previous_page_number }}">{{ answers.previous_page_number }}</a></li>
        {% endif %}
          <li><a href="{{url}}&answer_id={{ answers.number }}">{{ answers.number }}</a></li>
        {% if answers.has_next %}
          <li><a href="{{url}}&answer_id={{ answers.next_page_number}} ">{{answers.next_page_number}}</a></li>
        {% endif %}
        {% if answers.number < pagenum_minus_one %}
          <li><a href="{{url}}&answer_id={{ answers.paginator.num_pages }}">{{ answers.paginator.num_pages }}</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
  {% endif %}
{% endblock %}

{% block scripts %}
  <script type="text/javascript" src="/cookie/jquery.cookie.js"></script>
  <script type="text/javascript">
    var csrftoken = $.cookie('csrftoken')
    $.ajaxSetup({
          beforeSend: function(xhr, settings) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken)
          }
        });
        
    var del_func = function() {
      var answer = $(this).closest('.answer');
      $.post("/delete_answer", {id: $(this).data('id')})
      .done(function(response) {
          if(response.status == 'OK')
            answer.remove();
          else ;
        });
    }
        
    var like_func = function() {
        var like = $(this)
        $.post("/like", {type: like.data('type'), id: like.data('id')})
          .done(function(response) {
              $('.js_like_count').text(response.rating)
              console.log(response)
              $('.js_like').removeClass('like_'+$('.js_like').data('type')).addClass('like_'+response.status)
              $('.js_like').data('type', response.status)
            });
          }
            
    var correct_func = function() {
      var checkbox = $(this)
      var _id = $(this).parent().children('.js_correct_id').val()
      var _type = 'uncorrect'
      if (checkbox.is(':checked'))
        _type = 'correct'
      $.post("/set_correct", {type: _type, id: _id}).done(function(response) {
          if (response.status == 'OK') {
            var answer = checkbox.closest('.answer')
            if (response.answ_is_correct == true) {
              answer.addClass('alert-success')
              checkbox.prop('checked', true)
            } else {
              answer.removeClass('alert-success')
              checkbox.prop('checked', false)
            }
          } else {
            if (checkbox.is(':checked'))
              checkbox.prop('checked', false)
            else
              checkbox.prop('checked', true)
          }
        })
    };

    $('.js_like').on('click', like_func);

    $('.js_correct .js_correct_input').on('click', correct_func);
    
    $('.answer_form').submit(function() {
      var q_id = $(this).find('.q_id').val();
      var content = $(this).find('#id_content').val();
      $.post('/answer', {content: content, q_id: q_id})
      .done(function(response) {
        if (response.status == 'OK') {
          var answ_div = $("<div>")
          answ_div.addClass("answer").attr('id', 'answer_'+response.answ_id.toString())
          var info = $("<div>")
          info.addClass("info")
          var img = $("<img>").addClass("img-thumbnail").attr('height', 50)
          .attr('width', 50).attr('alt', 'Avatar').attr('src', response.userimg)
          var span1 = $("<span>").addClass("answ_author").text(response.username)
          var span2 = $("<span>").addClass('answ_date').text(response.datetime)
          var span3 = $("<span>").addClass('js_answer_delete').attr('data-id', response.answ_id.toString());
          span3.html('<span class="glyphicon glyphicon-trash"></span>').on('click', del_func);
          info.append(img).append(span1).append(span2).append(span3);
          answ_div.append(info).append(content)
          
          {% if user == question.author %}
          var form = $("<form>")
          form.addClass("js_correct")
          var input_id = $("<input>").addClass("js_correct_id").attr("type", "hidden").attr("value", response.answ_id.toString()).attr("name", "id")
          var input_chb = $("<input>").addClass("js_correct_input").attr("type", "checkbox").attr("value", "set").attr("name", "checker").attr("autocomplete", "off").on('click', correct_func)
          form.append(input_id).append(input_chb).append("Correct")
          answ_div.append(form)
          console.log(answ_div)
          {% endif %}
          
          $('#answer_list').prepend(answ_div)
        } else {
          console.log('error')
        }
      });
      return false;
    })
    
    $('.js_answer_delete').on('click', del_func);
  </script>
{% endblock %}

ask/templates/question_info.html
<div class="question row">
  <div class="question_side col-md-2">
    <div class="question_side_wrapper">
      <img src="{{question.author.avatar.url}}" width="50" height="50" class="img-thumbnail" alt="Avatar">
      
      <div>
        <span class="glyphicon glyphicon-thumbs-up"></span>
        <span class="js_like_count">
          {{ question.rating }}
        </span>
        {% if false %}
        {% csrf_token %}
        <span class="js_like like like_{{ question.liketype }}" data-id="{{ question.id }}" data-type="{{ question.liketype }}">
          <span class="glyphicon glyphicon-heart"></span>
        </span>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="question_body col-md-10">
    <div class="question_text row container-fluid">
        <h2>
          <a href="/question?id={{ question.id }}">
            {{ question.title|escape }}
          </a>
        </h2>
        <p>
          {{ question.content|truncatechars:140|truncatewords:50|escape }}
        </p>
    </div>
    <div class="question_meta row">
      <div class="question_answer col-md-3">
        <a href="/question?id={{ question.id }}&action=answer">answer ({{ question.answer_set.count }})</a>
      </div>
      <div class="question_tags col-md-7">
        Tags: <ul class="tag-list">{% for tag in question.tags.all %} <li class="tag"><a href="/tag/{{ tag.word|escape }}">{{ tag.word|escape }}</a>,</li> {% endfor %}</ul>
      </div>
    </div>
  </div>
</div>

ask/templates/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}
{% block main %}
  <div class="col-md-8">
  <h1>Register</h1>
  <div class="alert alert-danger" id="alert" style="display:none;">
    <a class="close">&times;</a>
    <div class="alert_message"></div>
  </div>
  <form action="" method="POST" style="width:200px; margin:20px 0;" id="reg_form">{% csrf_token %}
    {{ regform.as_p }}
    <div class="form-group">
      <input type="submit" value="Submit" class="btn btn-primary">
    </div>
  </form>
{% endblock %}

{% block scripts %}
  <script type="text/javascript" src="/cookie/jquery.cookie.js"></script>
  <script type="text/javascript">
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        xhr.setRequestHeader("X-CSRFToken", $.cookie('csrftoken'))
      }
    });
    $("#reg_form").submit(function(){
      var form = $(this)
      var _username = form.find("#id_username").val()
      var _email = form.find("#id_email").val()
      var _password = form.find("#id_password").val()
      $.post(window.location.href, {username:_username, email: _email, password: _password})
      .done(function(data) {
        if (data.status == 'OK') {
          al = $('#alert')
          al.show().removeClass('alert-danger').addClass('alert-success')
          am = al.children(".alert_message")
          am.empty();
          am.text('You have been successfully registered!');
          setTimeout(
          function(){
            window.location.href = location.protocol + '//'+location.host+data.redirect;},
          3000);
        } else {
          al = $('#alert')
          al.show().removeClass('alert-success').addClass('alert-danger')
          am = al.children(".alert_message")
          am.empty()
          data.info.forEach(function(element, index, array) {
            am.append("<strong>"+element[0]+"</strong><br/>"+element[1]+"<br/>");
          })
        }
      })
      return false;
    });
    $('.close').click(function() {
      $('.alert').hide();
    })
  </script>
{% endblock %}

ask/templates/search.html
{% extends "base.html" %}
{% block title %}Search{% endblock %}

{% load question_info %}
{% block main %}
  <div class="row">
    <h1 class="col-md-8">Questions for your search: {{query | escape}}</h1>
  </div>
  {% for question in question_list %}
    {% question_info question %}
  {% endfor %}
  <div class="row">
    <div class="col-md-12">
      <ul class="pagination">
        {% if question_list.number > 2 %}
          <li><a href="{{url | escape}}?page=1">1</a></li>
        {% endif %}
        {% if question_list.has_previous %}
          <li><a href="{{url | escape}}?page={{ question_list.previous_page_number }}">{{ question_list.previous_page_number }}</a></li>
        {% endif %}
          <li><a href="{{url | escape}}?page={{ question_list.number }}">{{ question_list.number }}</a></li>
        {% if question_list.has_next %}
          <li><a href="{{url | escape}}?page={{ question_list.next_page_number}} ">{{question_list.next_page_number}}</a></li>
        {% endif %}
        {% if question_list.number < pagenum_minus_one %}
          <li><a href="{{url | escape}}?page={{ question_list.paginator.num_pages }}">{{ question_list.paginator.num_pages }}</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
{% endblock %}

{% block scripts %}
  <script type="text/javascript" src="/cookie/jquery.cookie.js"></script>
  <script type="text/javascript">
  var csrftoken = $.cookie('csrftoken')
  $.ajaxSetup({
    beforeSend: function(xhr, settings) {
      xhr.setRequestHeader("X-CSRFToken", csrftoken)
    }
  });
        
  $('.js_like').on('click', function() {
    var like = $(this)
    $.post("/like", {type: like.data('type'), id: like.data('id')})
      .done(function(response) {
          like.parent().children('.js_like_count').text(response.rating)
          like.removeClass('like_'+$('.js_like').data('type')).addClass('like_'+response.status).data('type', response.status)
        })
  });
  </script>
{% endblock %}

ask/templates/signup.html
{% extends "base.html" %}
{% block title %}Settings{% endblock %}
{% block main %}
  <div class="col-md-8">
  <h1>Settings: {{user.name|escape}}</h1>
  <div class="alert" id="alert" style="display:none;">
    <a class="close">&times;</a>
    <div class="alert_message"></div>
  </div>
  <form action="" method="POST" style="width:200px; margin:20px 0;" class="signup_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="form-group">
      <input type="submit" value="Save" class="btn btn-primary">
    </div>
  </form>
{% endblock %}

{% block scripts %}
  <script type="text/javascript" src="/cookie/jquery.cookie.js"></script>
  <script type="text/javascript">
   /* $.ajaxSetup({
        beforeSend: function(xhr, settings) {
          xhr.setRequestHeader("X-CSRFToken", $.cookie('csrftoken'))
        }
      })
    $('.signup_form').on('submit', function() {
      var form = $(this);
      var msgbox = $('.alert');
      $('.close').click();
      $.post('', form.serialize() )
      .done(function(response) {
        if (response.status=='OK') {
          msgbox.removeClass('alert-danger').addClass('alert-success')
        } else {
          msgbox.removeClass('alert-success').addClass('alert-danger')
        }
        form.find('#id_username').text(response.username)
        form.find('#id_email').text(response.email)
        $('#user_avatar').attr('src', response.src)
        msgbox.find('.alert_message').text(response.message)
        msgbox.show()
      })
      return false;
    });
    $('.close').on('click', function() {
      $(this).parent().hide();
    })*/
  </script>
{% endblock %}

ask/templates/tag_list.html
{% extends "base.html" %}
{% block title %}Main page{% endblock %}

{% load question_info %}
{% block main %}
  <div class="row">
    <h1 class="col-md-8">Tag: {{ tag.word | escape }}</h1>
  </div>
  Order by: <a href="/?order=date">date</a> <a href="/?order=rating">rating</a>
  {% for question in question_list %}
    {% question_info question %}
  {% endfor %}
  <div class="row">
    <div class="col-md-12">
      <ul class="pagination">
        {% if question_list.number > 2 %}
          <li><a href="{{url|escape}}?page=1">1</a></li>
        {% endif %}
        {% if question_list.has_previous %}
          <li><a href="{{url|escape}}?page={{ question_list.previous_page_number }}">{{ question_list.previous_page_number }}</a></li>
        {% endif %}
          <li><a href="{{url|escape}}?page={{ question_list.number }}">{{ question_list.number }}</a></li>
        {% if question_list.has_next %}
          <li><a href="{{url|escape}}?page={{ question_list.next_page_number}} ">{{question_list.next_page_number}}</a></li>
        {% endif %}
        {% if question_list.number < pagenum_minus_one %}
          <li><a href="{{url|escape}}?page={{ question_list.paginator.num_pages }}">{{ question_list.paginator.num_pages }}</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
{% endblock %}